nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['*']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': ~
